apiVersion: v1
entries:
  hl7-resource-generator:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-07-27T22:40:55.568414-05:00"
    description: A Helm Chart to deploy the Alvearie HL7 Resource Generator service.  This service will convert HL7 data to FHIR.
    digest: f4ac5c902490c7ac6965b5fe36ceb5f6d0e155b079049cd4ca404152b1c3efad
    home: https://github.com/Alvearie/hl7-resource-generator-service
    keywords:
    - ibm
    - alvearie
    - hl7
    - fhir
    maintainers:
    - email: pbhallam@us.ibm.com
      name: Pushpa Bhallamudi
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: hl7-resource-generator
    type: application
    urls:
    - hl7-resource-generator-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-07-27T22:40:55.568005-05:00"
    description: A Helm Chart to deploy the Alvearie HL7 Resource Generator service.  This service will convert HL7 data to FHIR.
    digest: 45b23c5dd93ef86db0fd6079406eb8da9b656350240d2baf7403a015c3a59899
    home: https://github.com/Alvearie/hl7-resource-generator-service
    keywords:
    - ibm
    - alvearie
    - hl7
    - fhir
    maintainers:
    - email: pbhallam@us.ibm.com
      name: Pushpa Bhallamudi
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: hl7-resource-generator
    type: application
    urls:
    - hl7-resource-generator-0.1.0.tgz
    version: 0.1.0
generated: "2021-07-27T22:40:55.567463-05:00"
